<option value="Vehicles">Vehicles</option>
<option value="Blog">Blog</option>
<option value="Travel">Travel</option>
<option value="Personal Development">Personal Development</option>
<option value="Politics">Politics</option>
<option value="Sports">Sports</option>
<option value="Entertainments">Entertainments</option>
<option value="TV">TV</option>
<option value="Religion">Religion</option>
<option value="Weather">Weather</option>
<option value="Shopping">Shopping</option>